### ISSUE TITLE
no 'build' directory found on skesa branch in tools/skesa

### ISSUE THREAD

**Issue by pcantalupo** [ncbi/ngs-tools#9]
Hello,
I'm trying to install skesa. I cloned the repo as per README.md. Then had to checkout the skesa branch (which is not in the readme). Now I cannot find the `build` directory in the `tools/skesa` folder. Am I missing something? Thank you  Paul

**Comment by kwrodarmer** [comment]
apt-get update
  apt-get install -y git gcc g++ make libboost-all-dev
  
  git clone https://github.com/ncbi/ncbi-vdb.git
  git clone https://github.com/ncbi/ngs.git
  
  ( cd ngs ; ./configure ; make ; make install )
  ( cd ncbi-vdb ; ./configure ; make ; make install )

  git clone https://github.com/ncbi/ngs-tools.git
  cd ngs-tools
  ./configure

  git checkout skesa
  cd tools/skesa
  export BOOST_LIBPATH=/usr/lib/x86_64-linux-gnu
  export NGS_LIBPATH=/usr/local/ngs/ngs-sdk/lib64
  export NCBI_LIBPATH=/usr/local/ncbi/ncbi-vdb/lib64
  make skesa

Note that you have to have boost available...

**Comment by kwrodarmer** [comment]
I have updated the README.skesa file with these instructions.

**Comment by pcantalupo** [comment]
Thanks for the quick update! I hope to try this tonight

**Comment by NRCScientificIT** [comment]
Hello,
I tried the install/compliation as described here but I still have an error with the "make skesa" command:

/usr/include/boost/variant/detail/initializer.hpp:104:24: note:   no known conversion for argument 2 from ‘std::remove_reference<DeBruijn::IntegerTemplate&>::type {aka DeBruijn::IntegerTemplate}’ to ‘boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::make_initializer_node::apply<boost::mpl::pair<boost::detail::variant::initializer_root, mpl_::int_<0> >, boost::mpl::l_iter<boost::mpl::list16<DeBruijn::LargeInt<1>, DeBruijn::LargeInt<2>, DeBruijn::LargeInt<3>, DeBruijn::LargeInt<4>, DeBruijn::LargeInt<5>, DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<1> >, boost::mpl::l_iter<boost::mpl::list15<DeBruijn::LargeInt<2>, DeBruijn::LargeInt<3>, DeBruijn::LargeInt<4>, DeBruijn::LargeInt<5>, DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<2> >, boost::mpl::l_iter<boost::mpl::list14<DeBruijn::LargeInt<3>, DeBruijn::LargeInt<4>, DeBruijn::LargeInt<5>, DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<3> >, boost::mpl::l_iter<boost::mpl::list13<DeBruijn::LargeInt<4>, DeBruijn::LargeInt<5>, DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<4> >, boost::mpl::l_iter<boost::mpl::list12<DeBruijn::LargeInt<5>, DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<5> >, boost::mpl::l_iter<boost::mpl::list11<DeBruijn::LargeInt<6>, DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<6> >, boost::mpl::l_iter<boost::mpl::list10<DeBruijn::LargeInt<7>, DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<7> >, boost::mpl::l_iter<boost::mpl::list9<DeBruijn::LargeInt<8>, DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<8> >, boost::mpl::l_iter<boost::mpl::list8<DeBruijn::LargeInt<9>, DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<9> >, boost::mpl::l_iter<boost::mpl::list7<DeBruijn::LargeInt<10>, DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<10> >, boost::mpl::l_iter<boost::mpl::list6<DeBruijn::LargeInt<11>, DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<11> >, boost::mpl::l_iter<boost::mpl::list5<DeBruijn::LargeInt<12>, DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<12> >, boost::mpl::l_iter<boost::mpl::list4<DeBruijn::LargeInt<13>, DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<13> >, boost::mpl::l_iter<boost::mpl::list3<DeBruijn::LargeInt<14>, DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node, mpl_::int_<14> >, boost::mpl::l_iter<boost::mpl::list2<DeBruijn::LargeInt<15>, DeBruijn::LargeInt<16> > > >::initializer_node::param_T {aka const DeBruijn::LargeInt<15>&}’
make: *** [skesa.o] Error 1

**Comment by bioinfoacademy** [comment]
I get the same error like @NRCScientificIT. 
@kwrodarmer could you please help ?
Thanks in advance.
